version: '3'
services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3336:3336"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./.env:/app/.env 
    environment:
      - NODE_ENV=production
    command: npm start